# Generated by Django 5.1.6 on 2025-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Satış", "Satış"),
                            ("Pazarlama", "Pazarlama"),
                            ("Finans", "Finans"),
                            ("İK", "İK"),
                        ],
                        default="Satış",
                        max_length=50,
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(default="Bilinmiyor", max_length=100),
                ),
                ("title", models.CharField(default="Bilinmiyor", max_length=100)),
                ("value", models.CharField(default="Bilinmiyor", max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[("dis", "Dış Data"), ("ic", "İç Data")],
                        default="dis",
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ManagerBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Satış", "Satış"),
                            ("Pazarlama", "Pazarlama"),
                            ("Finans", "Finans"),
                            ("İK", "İK"),
                        ],
                        default="Satış",
                        max_length=50,
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(default="Bilinmiyor", max_length=100),
                ),
                ("info_title", models.CharField(default="Bilinmiyor", max_length=100)),
                ("value", models.CharField(default="Bilinmiyor", max_length=100)),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1. Ay"),
                            (2, "2. Ay"),
                            (3, "3. Ay"),
                            (4, "4. Ay"),
                            (5, "5. Ay"),
                            (6, "6. Ay"),
                            (7, "7. Ay"),
                            (8, "8. Ay"),
                            (9, "9. Ay"),
                            (10, "10. Ay"),
                            (11, "11. Ay"),
                            (12, "12. Ay"),
                        ],
                        default=1,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(default=2025)),
            ],
        ),
    ]
