# Generated by Django 5.1.6 on 2025-07-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departmanlar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datarecord",
            name="department",
            field=models.CharField(
                choices=[
                    ("Dış Ekip-1 (Murat)", "Dış Ekip-1 (Murat)"),
                    ("Dış Ekip-2 (Mertcan)", "Dış Ekip-2 (Mertcan)"),
                    ("Karşılama Ekibi (Ece)", "Karşılama Ekibi (Ece)"),
                    ("Dönüşüm Ekibi (Alper)", "Dönüşüm Ekibi (Alper)"),
                    (
                        "Yatırımlı Pasif Ekibi (Asuman)",
                        "Yatırımlı Pasif Ekibi (Asuman)",
                    ),
                    ("Retation Ekibi (Asuman)", "Retation Ekibi (Asuman)"),
                ],
                default="Dış Ekip-1 (Murat)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="managerbonus",
            name="department",
            field=models.CharField(
                choices=[
                    ("Dış Ekip-1 (Murat)", "Dış Ekip-1 (Murat)"),
                    ("Dış Ekip-2 (Mertcan)", "Dış Ekip-2 (Mertcan)"),
                    ("Karşılama Ekibi (Ece)", "Karşılama Ekibi (Ece)"),
                    ("Dönüşüm Ekibi (Alper)", "Dönüşüm Ekibi (Alper)"),
                    (
                        "Yatırımlı Pasif Ekibi (Asuman)",
                        "Yatırımlı Pasif Ekibi (Asuman)",
                    ),
                    ("Retation Ekibi (Asuman)", "Retation Ekibi (Asuman)"),
                ],
                default="Dış Ekip-1 (Murat)",
                max_length=50,
            ),
        ),
    ]
