# Generated by Django 5.1.6 on 2025-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departmanlar", "0002_alter_datarecord_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datarecord",
            name="data_type",
            field=models.CharField(
                choices=[("dis", "Dış Data"), ("ic", "İç Data")],
                default="dis",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="datarecord",
            name="value",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="managerbonus",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="managerbonus",
            name="value",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="managerbonus",
            name="year",
            field=models.IntegerField(default=2025),
        ),
    ]
