# Generated by Django 5.2.4 on 2025-09-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departmanlar', '0003_alter_datarecord_data_type_alter_datarecord_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departman')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kişi',
                'verbose_name_plural': 'Kişiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(verbose_name='Mesaj İçeriği')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Toplam Alıcı')),
                ('success_count', models.IntegerField(default=0, verbose_name='Başarılı Gönderim')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Başarısız Gönderim')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
                ('recipients', models.ManyToManyField(to='departmanlar.contact', verbose_name='Alıcılar')),
            ],
            options={
                'verbose_name': 'Toplu Mesaj',
                'verbose_name_plural': 'Toplu Mesajlar',
                'ordering': ['-sent_at'],
            },
        ),
    ]
