# Generated by Django 5.2.4 on 2025-07-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Veri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("deger", models.CharField(max_length=200)),
                ("tarih", models.DateField(auto_now_add=True)),
                (
                    "departman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departmanlar.departman",
                    ),
                ),
            ],
        ),
    ]
