# Generated by Django 5.2.4 on 2025-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departmanlar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departman",
            name="isim",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="veri",
            name="baslik",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="veri",
            name="deger",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="veri",
            name="tarih",
            field=models.DateField(),
        ),
    ]
